spring.application.name=SC-WebApp-Mall
spring.datasource.url=jdbc:mariadb://localhost:3306/market
spring.datasource.username=projectmarket
spring.datasource.password=projectmarketgarden2024
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database.platform=org.hibernate.dialect.MariaDBDialect